Algo-sadang/assignments

daeun/src/week02/Q29813_Daeun_Kim.java
daeun/src/week02/week02.iml

week02(큐) : 문제풀이

---

huipyo/src/week02/Q29813_Huipyo_Hong.java
huipyo/src/week02/Q5464_Huipyo_Hong.java

둘째주 과제 제출합니다.

---

huipyo/src/week03/Q3190_Huipyo_Hong.java

셋째주 과제 제출합니다.

---

bokyung/src/week04/Q1182_Bokyung.java
bokyung/src/week04/Q21937_Bokyung.java

21937번: 예제도 맞고 GPT한테 예제 만들어 달라해서 테스트해도 1퍼센트에서 틀렸다고 나오는데 어디서 틀렸는지 모르겠어서 일단 올립니다ㅜㅜ

Week04 submit(21937_unsolved)

---

huipyo/src/week04/Q1182_Huipyo_Hong.java
huipyo/src/week04/Q21937_Huipyo_Hong.java

넷째주 과제 제출합니다. 

---

huipyo/src/week06/Q3085_Huipyo_Hong.java

첫번째 Commit은 제출했을때 틀렸습니다로 기록.
이후 캔디 체크하는 과정에서 minu님 코드에 check()메소드 참고해서 제출하니 통과가 됐습니다.
check()메소드에 대한 동작과정은 리뷰가 필요합니다

다섯째주 과제 제출합니다.

---

minu/src/week07/Q15486_Minu.java

주어진 퇴사까지의 일자가 N 일때
상담 완료기간과 상담금액이 담기는 consulting 2차원 배열을 
일자가 1부터 시작하는것을 착안하여 아래처럼 선언
consulting = new int[N + 1][2]; 
최대 누적액이 담기는 dp 1 차원 배열은 아래처럼 선언
dp = new int[N + 1];
시작 인덱스를 1로 하여 N 만큼 루프를 돌며,
dp[N]에 상담한 최대 누적액이 담기게 했습니다.

Q15486 과제 제출

---

daeun/src/daeun.iml
daeun/src/week07/Q15486_Daeun_Kim.java

Scanner 사용시 느려서 BufferedReader 사용했습니다

week07(DP) : 15486 과제제출

---

.idea/modules.xml
hyeonseon/.gitignore
hyeonseon/hyeonseon.iml
hyeonseon/src/week08/Q92344_Hyeonseon.java

어디에 누적합을 적용시킬 수 있을까 고민하다가 실패했던 케이스까지 함께 올립니다🤣
카카오는 풀이 없이는 안되네요....
```
(x1, y1)+n, (x1, y2+1)-n
(x2+1, y1)-n, (x2+1, y2+1)+n
```
풀이 본 후 적용한 접근법입니다.
<br>
- [접근방법](https://school.programmers.co.kr/questions/25471)
- [2022 카카오 신입 공채 1차 온라인 코딩테스트 for Tech developers 문제해설](https://tech.kakao.com/2022/01/14/2022-kakao-recruitment-round-1/#%EB%AC%B8%EC%A0%9C-6-%ED%8C%8C%EA%B4%B4%EB%90%98%EC%A7%80-%EC%95%8A%EC%9D%80-%EA%B1%B4%EB%AC%BC)

update: 8주차 누적합 과제

---

daeun/src/week08/P192344_Daeun_Kim.java

전에 파이썬으로 풀어본 적 있는 문제입니다.
당시에 풀이를 참고했었어요
알고리즘 분류가 누적합인지 주어지지 않았다면 전혀 못 떠올렸을 거 같네용😅

week08(누적합) : 프로그래머스 92344 문제풀이

---

jinhong/src/week08/prefix_sum/Q82344_Jinhong_Jang.java

[week08(누적합)] 프로그래머스 92344

---

huipyo/src/week08/Q92344_Huipyo_Hong.java

처음엔 브루트포스로 접근하여 정확성은 다 맞았으나 효율성에서 틀렸습니다.
이후 해설을 보고 구현하니 해결되네요.
이차원배열에서의 누적합 구하는 방법을 알수 있는 문제인거 같습니다.

여덟번째주 과제 제출합니다.

---

jinhong/.gitignore
jinhong/jinhong.iml
jinhong/src/week09/Q1459_Jinhong_Jang.java

이동 방법(직선, 대각선)에 집중하여 생각하니, 답을 수월하게 찾을 수 있었습니다

[week09(그리디)] boj 1459

---

daeun/src/week09/Q1459_Daeun_Kim.java

week09(그리디) : 백준 1459 문제풀이

---

hyeonseon/src/week09/Q1459_Hyeonseon.java

0,0 -> 0,2 로 이동하는 대각선의 늪에 빠졌었네요 허허
백준에 제출한 버전은 `solution()` 입니다

update: 9주차 그리디 과제

---

huipyo/src/week06/Q3085_Huipyo_Hong.java
huipyo/src/week09/Q1459_Huipyo_Hong.java

다익스트라 써서 최단거리 구하기로 접근했습니다.
예제에 있는 답은 예제6번 10000000 50000000 800 901 제외하고 잘 나오는것 확인했으나 시간 초과 나올거 같아 제출은 아직 못했습니다.

아홉번째주 과제 제출합니다.

---

daeun/src/week10/Q2805_Daeun_Kim.java

스터디 시간에 풀었던 문제들과 비슷해서
금방 풀 수 있었습니다~!

week10(이분탐색) : 백준 2805 문제풀이

---

jinhong/src/week10/Q2805_Jinhong_Jang.java

했던 문제와 비슷해서 했던 문제를 보고 시도했습니다.
나무를 자르고 남는 길이와 자른 목재 길이가 헷갈려 많이 헤맸습니다 ㅠㅠ
+
역시 주어진 조건을 꼼꼼히 파악하는 것이 중요한 것 같습니다.
타입을 고려하지 않아 시간이 조금 걸렸습니다.

[week10(이분탐색)] boj 2805

---

minu/src/week10/Q2805_Minu.java

루프 변수의 최소높이와 최대높이를 설정하고, 중간값을 구한뒤에 
while 문안에서
이진탐색 함수를 사용해 정답을 찾도록 진행했습니다.

Q2805 과제 풀이

---

hyeonseon/src/week10/Q2805_Hyeonseon.java

update: 10주차, 2805번 나무 자르기

---

huipyo/src/week09/Q1459_Huipyo_Hong.java
huipyo/src/week10/Q2805_Huipyo_Hong.java

min max값을 구한후 이분탐색을 구합니다.
방식은 upperbound입니다.

열번째주 과제 제출합니다.

---

huipyo/src/week11/Q14246_Huipyo_Hong.java

입력으로부터 배열의 크기와 배열의 요소들, 그리고 k 값을 받습니다.
입력된 배열을 순회하면서 각 위치까지의 누적 합을 계산하여 배열에 저장합니다.
이중 반복문을 사용하여 모든 가능한 구간에 대해 구간 합을 계산하고, 그 합이 k보다 큰 경우 count를 증가시킵니다.
최종적으로 count 값을 출력합니다.

열한번째주 과제 제출합니다.

---

jinhong/src/week11/Q14246_Jinhong_Jang.java
minu/src/week11/Q14246_Minu.java

11주차 삭제된 PR 내용 추가
